# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apkgo < Formula
  desc "Upload apk to anywhere"
  homepage "https://apkgo.com.cn"
  version "1.0.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KevinGong2013/apkgo/releases/download/v1.0.4/apkgo_Darwin_x86_64.tar.gz"
      sha256 "e8f0641b3506164aca74165465266c6cf854f4649a7784c019c7a06f51a77588"

      def install
        bin.install "apkgo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KevinGong2013/apkgo/releases/download/v1.0.4/apkgo_Darwin_arm64.tar.gz"
      sha256 "7262a593d3de64595437e5fb36f1e759c9fe68ba0b73d640c65e5c73e4b6f642"

      def install
        bin.install "apkgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KevinGong2013/apkgo/releases/download/v1.0.4/apkgo_Linux_arm64.tar.gz"
      sha256 "06c33f2098ac8ad72811c0f9fe0f460f070df9cfd44d5075b5a81c6cc16b580a"

      def install
        bin.install "apkgo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KevinGong2013/apkgo/releases/download/v1.0.4/apkgo_Linux_x86_64.tar.gz"
      sha256 "881591e06e8a3703f18790c379b74d86683e97832a82298876d075f3c1c6674b"

      def install
        bin.install "apkgo"
      end
    end
  end
end
