# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apkgo < Formula
  desc "Upload apk to anywhere"
  homepage "https://apkgo.com.cn"
  version "0.9.0"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KevinGong2013/apkgo/releases/download/0.9.0/apkgo_Darwin_x86_64.tar.gz"
      sha256 "ad0e5ec1382fda449afca5b358783cfdd4c2f898d5684df44882d5a8d2ec9dc6"

      def install
        bin.install "apkgo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KevinGong2013/apkgo/releases/download/0.9.0/apkgo_Darwin_arm64.tar.gz"
      sha256 "d0d06afe05fa7f03b9a7b158bd5896fa58ed5def92ff9ab1857d885ed2ea6894"

      def install
        bin.install "apkgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KevinGong2013/apkgo/releases/download/0.9.0/apkgo_Linux_arm64.tar.gz"
      sha256 "4e9bcfe500ae9ad5dca57bfb6e64b751969e680816d33ff1ccb697db3ff1d11c"

      def install
        bin.install "apkgo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KevinGong2013/apkgo/releases/download/0.9.0/apkgo_Linux_x86_64.tar.gz"
      sha256 "647f669b6eb1e57cbdd4383a39c91ef7cc53451c562c492ee47882631b86c482"

      def install
        bin.install "apkgo"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/KevinGong2013/apkgo/releases/download/0.9.0/apkgo_Linux_armv6.tar.gz"
      sha256 "fb667b1448c45664af017c552bbf93e90fd7ecebdda0df7dbe7f8c20ca8d9b9f"

      def install
        bin.install "apkgo"
      end
    end
  end
end
