# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ApkgoCams < Formula
  desc "上传apk到七牛、并发布cams"
  homepage "https://apkgo.com.cn"
  version "1.0.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/YuxiaorMobileTeam/apkgo-cams/releases/download/1.0.5/apkgo-cams_Darwin_arm64.tar.gz"
      sha256 "cf6603c0f369fd6eba0f7d3248341ae17506a2e5192823275c10dbdda6bce458"

      def install
        bin.install "apkgo-cams"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/YuxiaorMobileTeam/apkgo-cams/releases/download/1.0.5/apkgo-cams_Darwin_x86_64.tar.gz"
      sha256 "a68d7dd76ca29a1bce9f5054557e638eaec49f9f70fc10ad5834376c8a0334fc"

      def install
        bin.install "apkgo-cams"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YuxiaorMobileTeam/apkgo-cams/releases/download/1.0.5/apkgo-cams_Linux_arm64.tar.gz"
      sha256 "ba27582f1cd82ee00f72a4593d22243fc09476c9af273cac974d1c29fe49c58f"

      def install
        bin.install "apkgo-cams"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/YuxiaorMobileTeam/apkgo-cams/releases/download/1.0.5/apkgo-cams_Linux_x86_64.tar.gz"
      sha256 "532ab2e0a192e02db5cd84242ddbcc43d619485adcdda9ffd9eb7246b8d27819"

      def install
        bin.install "apkgo-cams"
      end
    end
  end
end
