# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ApkgoCams < Formula
  desc "上传apk到七牛、并发布cams"
  homepage "https://apkgo.com.cn"
  version "1.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/YuxiaorMobileTeam/apkgo-cams/releases/download/1.0.1/apkgo-cams_Darwin_arm64.tar.gz"
      sha256 "37c65e95baf717beb1f488859ccd5c16dffdccdace23598022043335201094da"

      def install
        bin.install "apkgo-cams"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/YuxiaorMobileTeam/apkgo-cams/releases/download/1.0.1/apkgo-cams_Darwin_x86_64.tar.gz"
      sha256 "4a3ed9563a89e755d4671c6ae320e9ae28044fe1deef5dc0f15dd4744eab3a50"

      def install
        bin.install "apkgo-cams"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YuxiaorMobileTeam/apkgo-cams/releases/download/1.0.1/apkgo-cams_Linux_arm64.tar.gz"
      sha256 "58273969923b0b41b52ac4cea432cf5a6307efa393f73895f20b851502a8efb1"

      def install
        bin.install "apkgo-cams"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/YuxiaorMobileTeam/apkgo-cams/releases/download/1.0.1/apkgo-cams_Linux_x86_64.tar.gz"
      sha256 "88e976e56d8d1f03266f79fdbc48e5c4ddca4d958a5e794655b38be9957524d6"

      def install
        bin.install "apkgo-cams"
      end
    end
  end
end
