# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apkgo < Formula
  desc "Upload apk to anywhere"
  homepage "https://apkgo.com.cn"
  version "1.0.10"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/KevinGong2013/apkgo/releases/download/v1.0.10/apkgo_Darwin_arm64.tar.gz"
      sha256 "69f988787eda81b6d94f47f101af543e0d3643950ad1b4730399e861c7d4959a"

      def install
        bin.install "apkgo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KevinGong2013/apkgo/releases/download/v1.0.10/apkgo_Darwin_x86_64.tar.gz"
      sha256 "507713f1f81a3e5776986fa206bf2ff680baba72f7fa1be2fec3e2af2fdba08b"

      def install
        bin.install "apkgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KevinGong2013/apkgo/releases/download/v1.0.10/apkgo_Linux_arm64.tar.gz"
      sha256 "01507c12b3f801e132498349af074b8031c9478276a818097b8f1137d794c9f3"

      def install
        bin.install "apkgo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KevinGong2013/apkgo/releases/download/v1.0.10/apkgo_Linux_x86_64.tar.gz"
      sha256 "b1b165f4c920231b9b3a31b4d4bfde605654aac2fe7f62cb665ce6a2266e52a0"

      def install
        bin.install "apkgo"
      end
    end
  end
end
